PRIMS_START_ROW: 1
PRIMS_START_COL: 1
NUMBER_PATHS_ADD: 5
SWAMP_COST: 10
SAND_COST: 14
DEFAULT_COST: 5
EAT_COST: 2
COIN_COST: 1
SWAMP_PROBABILITY: 0.05
SAND_PROBABILITY: 0.06
EAT_PROBABILITY: 0.07
COIN_PROBABILITY: 0.08
