PRIMS_START_ROW: 1
PRIMS_START_COL: 1
NUMBER_PATHS_ADD: 5
SWAMP_COST: 10
SAND_COST: 14
DEFAULT_COST: 5
EAT_COST: 2
COIN_COST: 1
SWAMP_PROBABILITY: 0.05
SAND_PROBABILITY: 0.011
EAT_PROBABILITY: 0.018
COIN_PROBABILITY: 0.026
SELECTION_ATTEMPTS: 10
DEFAULT_MENU_NUMBER: 1
DEFAULT_MAZE_SIZE: 35
DIRECTIONS_LEFT_INDEX: 0
DIRECTIONS_RIGHT_INDEX: 1
INVALID_INPUT_MESSAGE: "Invalid input. Try again."
